version: '3.9'
services:
  nginx:
    image: nginx
    build: .
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - todoapp1

  todoapp1:
    container_name: todoapp1
    image: todoapp1:0.0.1
    build: .
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/todo
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - java_db
    ports:
      - 8080:8080

  java_db:
    container_name: java_db
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo
    ports:
      - 5432:5432